---

- hosts: webservers
  become: yes
  remote_user: vagrant
  tasks:

    - name: install httpd
      yum:
        update_cache: yes
        name: httpd
        state: installed

    - name: start httpd server
      service:
        name: httpd
        state: started

    - name: copy index.html file into my webserver
      copy:
        src: index.html
        dest: /var/www/html

    - name: copy file to remote server
      copy:
        src: /home/vagrant/file1
        dest: /tmp
        remote_src: yes

    - name: create a file & change ownership
      file:
        path: /home/vagrant/data
        state: touch
        owner: root
        group: vagrant
        mode: 0777

